[general]
token = ""

[categories]
    [categories.0]
    categoryId = "528139357723426818"

    autoText = true
    autoTextPrefix = "-"
    autoTextPosition = "bottom"

    autoVoice = true
    autoVoicePrefix = "Temp"
    autoVoiceSlots = 99
    autoVoiceChannelLimit = 20
    autoVoiceBitrate = 96000
    autoVoicePermissions = []
